# ========== Nginx ==========
[[redirects]]
from = "/nginx/*"
to = "https://npm.badd.eu.org:8008/:splat"
status = 200
force = true

# ========== PVE ==========
[[redirects]]
from = "/homelab/*"
to = "https://homelab.badd.eu.org:8008/:splat"
status = 200
force = true

# ========== istoreos ==========
[[redirects]]
from = "/istoreos/*"
to = "https://istoreos.badd.eu.org:8008/:splat"
status = 200
force = true
